logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 9000
  ssl:
    enabled: true
    key-store-type: PKCS12
    #    key-store: classpath:keystore/keystore.p12
    key-store: file:C:\Users\79925\java\openjdk-8u42-b03-windows-i586-14_jul_2022\java-se-8u42-ri\keystore.p12
    key-store-password: changeit
    protocol: TLS
    enabled-protocols: TLSv1.2