server:
  port: 8888

spring:
  datasource:
    username: postgres
    password: shiyinhong
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres?currentSchema=public
mybatis:
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true